name: Scrape Sreality

on:
  schedule:
    - cron: '0 8 * * *'  # Spustí se každý den v 8:00
  workflow_dispatch:      # Umožní i manuální spuštění

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create and verify credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        # Vytvoření credentials souboru
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        
        # Kontrola, zda soubor existuje a není prázdný
        if [ ! -s credentials.json ]; then
          echo "Chyba: credentials.json je prázdný!"
          exit 1
        fi
        
        # Kontrola, zda je soubor validní JSON
        if ! jq empty credentials.json 2>/dev/null; then
          echo "Chyba: credentials.json není validní JSON!"
          exit 1
        fi
        
        # Kontrola required fields
        if ! jq -e '.client_email and .private_key and .project_id' credentials.json > /dev/null; then
          echo "Chyba: V credentials.json chybí povinná pole!"
          exit 1
        fi
        
        echo "Credentials soubor je validní"
        echo "Project ID: $(jq -r .project_id credentials.json)"
        echo "Client email: $(jq -r .client_email credentials.json)"
    
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python sreality_scraper.py
      
    - name: Cleanup
      if: always()
      run: rm -f credentials.json