name: Scrape Sreality

on:
  schedule:
    - cron: '0 8 * * *'  # Spustí se každý den v 8:00
  workflow_dispatch:      # Umožní i manuální spuštění

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        echo "Credentials file created:"
        cat credentials.json | jq .
    
    - name: Run scraper
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python sreality_scraper.py
      
    - name: Cleanup
      if: always()
      run: rm -f credentials.json